#!/usr/bin/env bash
# setup-real-target-fork.sh — Anvil fork of BSC with recon hot wallet as watch target
# LOCAL SANDBOX: simulates real chain state; does NOT broadcast to mainnet.
set -euo pipefail

SANDBOX="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SANDBOX/../.." && pwd)"
PROFILES="$ROOT/artifacts/sandbox/target-profiles.json"
PROFILE="$ROOT/artifacts/sandbox/target-profile.json"

if [[ ! -f "$PROFILES" ]]; then
  python3 "$SANDBOX/generate-target-profile.py"
fi

HOT="$(python3 - <<PY
import json
from pathlib import Path
for p in [Path("$PROFILES"), Path("$PROFILE")]:
    if p.is_file():
        d = json.loads(p.read_text())
        if d.get("wallets"):
            print(d["wallets"][0]["address"]); raise SystemExit
        if d.get("primary_target"):
            print(d["primary_target"]["address"]); raise SystemExit
PY
)"
AUTH="$(python3 - <<PY
import json
from pathlib import Path
p = Path("$PROFILES")
if p.is_file():
    for w in json.loads(p.read_text()).get("wallets", []):
        if w.get("role") == "authority":
            print(w["address"]); raise SystemExit
p = Path("$PROFILE")
if p.is_file():
    print(json.loads(p.read_text()).get("related_targets", {}).get("authority", ""))
PY
)"
OUT="$SANDBOX/anvil.env"
FORK_RPC="${BSC_FORK_RPC:-https://bsc-dataseed.binance.org}"
PORT="${ANVIL_PORT:-8545}"
HOST="${ANVIL_HOST:-127.0.0.1}"
PID_FILE="${TMPDIR:-/tmp}/hexstrike-anvil-fork.pid"
LOG_FILE="${TMPDIR:-/tmp}/hexstrike-anvil-fork.log"

if ! command -v anvil >/dev/null 2>&1; then
  echo "[FAIL] anvil not found — install Foundry"
  exit 1
fi

# Stop plain anvil if running on same port
if [[ -f "${TMPDIR:-/tmp}/hexstrike-anvil.pid" ]]; then
  kill "$(cat "${TMPDIR:-/tmp}/hexstrike-anvil.pid")" 2>/dev/null || true
fi
if [[ -f "$PID_FILE" ]] && kill -0 "$(cat "$PID_FILE")" 2>/dev/null; then
  echo "[OK]   BSC fork already running (pid $(cat "$PID_FILE"))"
else
  echo "[start] Anvil BSC fork from $FORK_RPC"
  nohup anvil --host "$HOST" --port "$PORT" --chain-id 56 \
    --fork-url "$FORK_RPC" \
    >"$LOG_FILE" 2>&1 &
  echo $! >"$PID_FILE"
  sleep 3
fi

RPC="http://${HOST}:${PORT}"
curl -sf --max-time 5 "$RPC" -X POST -H "Content-Type: application/json" \
  -d '{"jsonrpc":"2.0","method":"eth_chainId","params":[],"id":1}' >/dev/null \
  || { echo "[FAIL] fork not responding — tail $LOG_FILE"; tail -20 "$LOG_FILE"; exit 1; }

BAL="$(cast balance "$HOT" --rpc-url "$RPC" 2>/dev/null || echo 0)"
NONCE="$(cast nonce "$HOT" --rpc-url "$RPC" 2>/dev/null || echo 0)"

cat >"$OUT" <<ENV
# REAL TARGET FORK — BSC hot wallet watch mode (no mainnet signing)
# Generated by setup-real-target-fork.sh — LOCAL FORK ONLY
RPC_URL=$RPC
UPSTREAM_RPC=$RPC
DIRECT_RPC_URL=$RPC
PROXY_PORT=8546
CHAIN_ID=56

# Watch target from artifacts/sandbox/target-profile.json
BOT_ADDRESS=$HOT
# No private key for third-party wallet — bot runs DRY_RUN / recon only
BOT_PRIVATE_KEY=
FUNDER_ADDRESS=${AUTH:-$HOT}

THRESHOLD_WEI=500000000000000000
MIN_GAS_WEI=10000000000000000
RESCUE_VALUE_WEI=1000000000000000000
POLL_INTERVAL_SEC=10

HARDENING_ENABLED=true
MAX_BALANCE_DELTA_WEI=0
ANOMALY_STALE_TIMEOUT_SEC=120
GUARD_RPC_TIMEOUT_SEC=10
DRY_RUN=true
TARGET_MODE=fork_watch
ENV

echo "[OK]   Real-target fork env: $OUT"
echo "       BOT_ADDRESS (hot wallet): $HOT"
echo "       BNB balance on fork: $BAL wei"
echo "       nonce: $NONCE"
echo "       DRY_RUN=true — no mainnet/main-fork broadcast without operator key"
echo ""
echo "Next: ./scripts/sandbox/run-target-recon.sh"

STATUS="$ROOT/artifacts/sandbox/target-fork-status.json"
mkdir -p "$(dirname "$STATUS")"
python3 - <<PY
import json
from datetime import datetime, timezone
from pathlib import Path
p = Path("$STATUS")
p.write_text(json.dumps({
    "generated_at": datetime.now(timezone.utc).isoformat(),
    "mode": "fork_watch",
    "bot_address": "$HOT",
    "rpc": "$RPC",
    "chain_id": 56,
    "dry_run": True,
    "env_file": "$OUT",
}, indent=2) + "\n")
print(f"[OK]   Status: {p}")
PY
